#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
	state=`pgrep -f "/usr/bin/zospusher/zospusher"`
	if [ ! -z "$state" ]; then
		restart
	else
		/usr/bin/zospusher/zospusher &
	fi
	echo "zospusher is starting now ..."
}

stop() {
	kill -9 `pgrep -f "/usr/bin/zospusher/zospusher"` 2>/dev/null
	echo "zospusher exit ..."
}

restart(){
	stop
	sleep 1
	start
	echo "restarted."
}